title: centos
url: "https://centos.github.io"
permalink: /:title/
markdown: kramdown
kramdown:
  typographic_symbols:
    ndash: "--"
    mdash: "---"

exclude:
  - README.md
  - Gemfile

remote_theme: just-the-docs/just-the-docs@v0.4.1
plugins:
  - jekyll-remote-theme

color_scheme: coreos

footer_content: 'Copyright &copy; <a href="https://www.redhat.com">Red Hat, Inc.</a>'

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/centos/centos.github.io"
gh_edit_branch: "main"
gh_edit_source: .
gh_edit_view_mode: "tree"

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
